//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Okul.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitap()
        {
            this.AlinanKitaplarr = new HashSet<AlinanKitaplarr>();
        }
    
        public int Id { get; set; }
        public string Adı { get; set; }
        public Nullable<int> SayfaSayisi { get; set; }
        public string KategoriAdı { get; set; }
        public string Yazar { get; set; }
        public Nullable<int> KitapYılı { get; set; }
        public Nullable<int> StokMiktari { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlinanKitaplarr> AlinanKitaplarr { get; set; }
    }
}
